import json
import sys
from pathlib import Path
import torch

import fire
from loguru import logger

from .caching import TranscodedModel
from .mlp_attribution import AttributionConfig, AttributionGraph


async def main(
    prompt="<cls> ACGTTG AAACGA CGCGCG GTTTCA GAAAGC AGTGGG GCATCG ACCGAT TGACCG GTAAAC TCCAGA CGCAGC ATCGGC ACGCAG TCAGTA AATGGC TCCGCT TGCAGA CGTTCC TGGTAA TCTTCC GGGATA TCCAGA TGCAGG GTCGAC TGAATA AACTTC TGCGCC AGCGGC GTTTTC GGATGC GAGAAC ACTTCA CTTACC GTGTCC TGCTCG ATCAGT TCTCCA TTGCTG ATGACC GCCACG CAATCA CAAATG CGCTTC ACAACG TCCATT TCGTGG GTGATC AACAGA ATCGTC AACCCC AGACGG CGGTTG ATGTCT TTCAGC AGTTCG AGAATA GAACGT GTCGTT GCCGGG TCCAGC GCGCTG GTGGCT TCATCA CACAGC AATACT TTGGGA TTGCTG GCTAAC GCACGG GCAATT GCCACA CGTTGT TTCTGC CCACCG GAAAGA TTCGAC GGGTAG CTATCA TGCTTA TCGCCA AGACCA ACCAAT GACAGC AATTCC GTCACG CGACGT TTGACC TCGTCT TTCGGT GTGTTG TCCAGC TCCAGC GGCAGA GCCACG TTGCCA AAAACA GTACGC GAAGAG AGCAGG TTAAAA TGCTGG AAAATC ATACCA ATCTGG CGGCGA GCTTTG GTCAAC TCGGAT TCTGAC AGCGTG GTCAGT TCCTGG CCATCG ACCAGC ACGCTA CCCTCG GTTGGG CGCTCC AGCAGG TTTACA CAACGT ATAAGC GTACTC TTACCC GCGCCT GAGGCA CCGATA ACGCCA TAAATT TGTCCA GCTGGC ACATGC AGGCTG ACGTTG TTCAAC GCCTGG ATGGTG CGGGTG CCCTGG TGGAAC ACTTTG GTGATA TTCGAA AGTTTT ATCATT GATTAT TTATTA TCGTCA TTAAGT TAGTCG TGGCAT CTCGAA TGCCTG AAACGG GCAACG CCGTCA ATGAAA TGGATG TTAAGG CATCCA GACGTC TAAATC AATCAG GTTTAT GCGAAG AGCACT TTCTTG CAGGTC GAAACA TGCGAT ACTAGC GTCACA TGCCTT ATTAAG GAGCTA TAAAAG GTGGCG AAGAGC GTACCC GCAATT TTTCTT GACCGT GATGGC ACCATT AATGTC GATCAC GGCTAT GTCCAT GAGATC GACAAC TTTGAA TTTATC GACGGT GTTATT GACGCC ATGCGC GAGCTA AAAAAA ATGGGC TTTGCG CTGGTG GTAGTA ACCAAC CAGTCT GGCATT GCTCGC GGTAAA TTTACC GAAGCA CAGTTT GAAACG CTGACC GAGTGG ATGGAC TGGTCG CTGGCG GACCGA GATGTC GATCTG GATGGT ATCTAT TATTGC CCGCAT CATCCG CAGGGT AGTGTT GAAGAG TTTCGC CAGGTC TGCGAT TGCCGC AAACCA CATCCG GGGATG CTTTTG TCAGCA CGCGAT TATTTG CATATT GATATG GCCGCT TCTTAT ATGGTG GGCGAT AAATTA GAAGAT ATGCAG GCAGCG GTTGCG GCGAAC GTGGGA ACAAAA GTGCTG GTGCGT ACGGGT AAACCT ATTACG CCTGAA GCAGAA AACGCG GCGGAT TGGGTG TTAAAT AGCCTG GCAGAC CTGCCG CAAGCG ATAAAA AAGCAG CAAAAA CCGGCA CAATGA TTAAAA GATGAG CGGTTG AAATAA AAATGC ATTTTT CCGCTT GTCTTC CTGAGC CGACTC CCTATA ATGCGC CTCCAT CGACAC GGCGGA TGTGAA TCACTT CACACA AACAGC CGGTTC GGTTGA AGAGAA AAATCC TGAAAT TCAGGG TTGACT CTGAAA GAGGAA AGCGTA ATATAC GCCACC TCGCGA CAGTGA GCTGAA AGCCGC GTCGCA ACTGCT CTTTAA CAATTT ATCAGA CAATCT GTGTGG GCACTC GAAGAT ACGGAT TCTTAA CGTCGC AAGACG AAAAAT GAATAC CAAGTC TCAAGA GTGAAC ACGTAA TTCATT ACAAAG TTTAAT TCTTTG AGCATC AAACTT TTAAAT TGAAGA GTTTGA TCATGG CTCAGA TTGAAC GCTGGC GGCAGG CCTAAC ACATGC AAGTCG AACGGT AACAGG AAGAAG CTTGCT TCTTTG CTGACG AGTGGC GGACGG GTGAGT AATGTC TGGGAA ACTGCC TGATGG AGGGGG ATAACT ACTGGA AACGGT AGCTAA TACCGC ATAACG TCGCAA GACCAA AGAGGG GGACCT TCGGGC CTCTTG CCATCG GATGTG CCCAGA TGGGAT TAGCTA GTAGGT GGGGTA ACGGCT CACCTA GGCGAC GATCCC TAGCTG GTCTGA GAGGAT GACCAG CCACAC TGGAAC TGAGAC ACGGTC CAGACT CCTACG GGAGGC AGCAGT GGGGAA TATTGC ACAATG GGCGCA AGCCTG ATGCAG CCATGC CGCGTG TATGAA GAAGGC CTTCGG GTTGTA AAGTAC TTTCAG CGGGGA GGAAGG GAGTAA AGTTAA TACCTT TGCTCA TTGACG TTACCC GCAGAA GAAGCA CCGGCT AACTCC GTGCCA GCAGCC GCGGTA ATACGG AGGGTG CAAGCG TTAATC GGAATT ACTGGG CGTAAA GCGCAC GCAGGC GGTTTG TTAAGT CAGATG TGAAAT CCCCGG GCTCAA CCTGGG AACTGC ATCTGA TACTGG CAAGCT TGAGTC TCGTAG AGGGGG GTAGAA TTCCAG GTGTAG CGGTGA AATGCG TAGAGA TCTGGA GGAATA CCGGTG GCGAAG GCGGCC CCCTGG ACGAAG ACTGAC GCTCAG GTGCGA AAGCGT GGGGAG CAAACA GGATTA GATACC CTGGTA GTCCAC GCCGTA AACGAT GTCGAC TTGGAG GTTGTG CCCTTG AGGCGT GGCTTC CGGAGC TAACGC GTTAAG TCGACC GCCTGG GGAGTA CGGCCG CAAGGT TAAAAC TCAAAT GAATTG ACGGGG GCCCGC ACAAGC GGTGGA GCATGT GGTTTA ATTCGA TGCAAC GCGAAG AACCTT ACCTGG TCTTGA CATCCA CAGAAC TTTCCA GAGATG GATTGG TGCCTT CGGGAA CTGTGA GACAGG TGCTGC ATGGCT GTCGTC AGCTCG TGTTGT GAAATG TTGGGT TAAGTC CCGCAA CGAGCG CAACCC TTATCT TTTGTT GCCAGC GGTCCG GCCGGG AACTCA AAGGAG ACTGCC AGTGAT AAACTG GAGGAA GGTGGG GATGAC GTCAAG TCATCA TGGCCC TTACGA CCAGGG CTACAC ACGTGC TACAAT GGCGCA TACAAA GAGAAG CGACCT CGCGAG AGCAAG CGGACC TCATAA AGTGCG TCGTAG TCCGGA TTGGAG TCTGCA ACTCGA CTCCAT GAAGTC GGAATC GCTAGT AATCGT GGATCA GAATGC CACGGT GAATAC GTTCCC GGGCCT TGTACA CACCGC <mask>",
    model_name="InstaDeepAI/nucleotide-transformer-v2-500m-multi-species",
    save_dir = Path("results"),
    transcoder_path = "/mnt/ssd-1/gpaulo/nucleotide/clt-training/checkpoints/5e-4-64x-k128-muon",
    cache_path = "none",
    name = "test-1-ts",
    scan = "default",
    remove_prefix = 0,
    pre_ln_hook = False,
    post_ln_hook = False,
    offload: bool = False,
    force_k: int = None,
    cache_features: bool = True,
    save_graph: bool = True,
    **kwargs,
):
    logger.remove()
    logger.add(sys.stderr, level="INFO")

    config = AttributionConfig(
        name=name,
        scan=scan,
        **kwargs
    )
    torch._functorch.config.donated_buffer = False

    model = TranscodedModel(
        model_name=model_name,
        transcoder_path=transcoder_path,
        device="cuda",
        pre_ln_hook=pre_ln_hook,
        post_ln_hook=post_ln_hook,
        offload=offload,
    )
    if force_k is not None:
        for transcoder in model.transcoders.values():
            transcoder.cfg.k = force_k
    transcoded_outputs = model([prompt] * config.batch_size)
    transcoded_outputs.remove_prefix(remove_prefix)

    attribution_graph = AttributionGraph(model, transcoded_outputs, config)
    attribution_graph.get_dense_features(cache_path)
    attribution_graph.flow()
    save_results = attribution_graph.save_graph(save_dir if save_graph else None)
    if not save_graph:
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)
        (save_dir / "results.json").write_text(json.dumps(save_results.to_dict()))
    if cache_features:
        attribution_graph.cache_features(save_dir)
        attribution_graph.cache_self_explanations(save_dir)
        await attribution_graph.cache_contexts(cache_path, save_dir)


if __name__ == "__main__":
    fire.Fire(main)
